@startuml
title Modelando o iPhone com UML por jucastrum

skinparam classAttributeIconSize 0

interface "Reprodutor Musical" as ReprodutorMusical {
  -Musica[] musicas
  +tocar(): void
  +pausar(): void
  +selecionarMusica(): void
}
note top of ReprodutorMusical
  Interface encarregada de implementar
  a funcionalidade de reprodução de 
  arquivos de áudio.
end note

interface "Aparelho Telefônico" as AparelhoTelefonico {
  -Contato[] contatos
  +redeMovelDisponivel(): Boolean
  +ligar(): void
  +atender(): void
  +iniciarCorreioVoz(): void
}
note top of AparelhoTelefonico
  Interface encarregada de implementar
  a funcionalidade de um telefone.
end note

class Musica {
  nome: String
  caminho: String
}
note top of Musica
  Classe responsável por 
  armazenar informações 
  das músicas.
end note

class Contato {
  nome: String
  numero: String
}
note top of Contato
  Classe responsável por 
  armazenar informações 
  de contato.
end note

interface "Navegador de Internet" as NavegadorInternet {
  +ConexaoComInternet(): Boolean
  +exibirPagina(): void
  +adicionarNovaAba(): void
  +atualizarPagina(): void
}
note top of NavegadorInternet
  Interface encarregada
  de implementar
  a funcionalidade 
  de um navegador.
end note

class IPhone {}

class Safari {}
class Chrome {}

class NokiaE62 {}
class BlackBerry {}

class Walkman {}
class Ipod {}

IPhone --> AparelhoTelefonico
IPhone --> NavegadorInternet
IPhone --> ReprodutorMusical
ReprodutorMusical --o Musica
AparelhoTelefonico <-- NokiaE62
AparelhoTelefonico <-- BlackBerry
AparelhoTelefonico --o Contato

ReprodutorMusical <-- Walkman
ReprodutorMusical <-- Ipod

NavegadorInternet <-- Safari
NavegadorInternet <-- Chrome

@enduml
